# PokePlugin Configuration
# Cost in server currency to poke someone
poke-cost: 50

# Cooldown in hours between pokes
cooldown-hours: 3

# Message Configuration
messages:
  no-balance: "§cYou need $%cost% to poke someone!"
  cooldown: "§eYou must wait §c%time% §ebefore poking again!"
  poked: "§bYou've been poked by §e%player%§b!"
  poke-success: "§aYou poked §e%target% §asuccessfully!"
  player-not-found: "§cThat player is not online!"
  self-poke: "§cYou can't poke yourself!"
  no-economy: "§cEconomy system not found! Pokes are free."
  reload-success: "§aPokePlugin configuration reloaded successfully!"
  no-permission: "§cYou don't have permission to use this command!"

# Notification Settings
notifications:
  # Show title/subtitle when poked
  title: true
  # Play sound when poked
  sound: true
  # Sound to play (ENTITY_EXPERIENCE_ORB_PICKUP, BLOCK_NOTE_BLOCK_PLING, etc.)
  sound-type: ENTITY_EXPERIENCE_ORB_PICKUP
  # Sound volume (0.0 - 1.0)
  sound-volume: 1.0
  # Sound pitch (0.5 - 2.0)
  sound-pitch: 1.0

# Title Configuration (if notifications.title is true)
title:
  main: "§b§lPOKED!"
  subtitle: "§eby %player%"
  fade-in: 10
  stay: 40
  fade-out: 10