name: PokePlugin
version: '${project.version}'
main: com.alan.pokePlugin.PokePlugin
api-version: '1.20'
author: AlanTheDev
website: https://github.com/Eldrath-Dev
description: Enhanced poke notification system for Minecraft servers
softdepend: [Vault, PlaceholderAPI]
folia-supported: true

commands:
  poke:
    description: Poke another player or manage settings
    usage: /<command> <player|@a|settings|allow|disable|block|unblock|reload>
    permission: pokeplugin.use

permissions:
  pokeplugin.use:
    description: Allows the use of /poke command
    default: true
  pokeplugin.settings:
    description: Allows access to poke settings GUI
    default: true
  pokeplugin.admin:
    description: Allows admin features like /poke @a
    default: op
  pokeplugin.bypass.cooldown:
    description: Bypass poke cooldown
    default: op
  pokeplugin.bypass.cost:
    description: Bypass poke cost
    default: op
  pokeplugin.reload:
    description: Reload plugin configuration
    default: op