# PokePlugin v2.0 Configuration
# Public Brand: PokeNotify
# Author: AlanTheDev

poke:
  # Sound to play when poked
  sound: ENTITY_EXPERIENCE_ORB_PICKUP
  sound-volume: 1.0
  sound-pitch: 1.0

  # Title shown when poked
  title:
    enabled: true
    main: "&aYou've been poked!"
    subtitle: "&eby {player}"
    fade-in: 10
    stay: 40
    fade-out: 10

  # Cooldown between pokes (in hours)
  cooldown: 3

  # Cost per poke (requires Vault)
  cost: 50

  # Allow admins to bypass privacy settings with /poke @a
  admin-bypass: true

database:
  # Database type (sqlite only for now)
  type: sqlite
  # Database file location (relative to plugin folder)
  file: data/pokedata.db

privacy:
  # Default privacy mode for new players
  # Options: ALLOW_ALL, DISABLED, CUSTOM
  default-mode: ALLOW_ALL

placeholders:
  # Enable PlaceholderAPI integration
  enabled: true

gui:
  # Enable GUI-based settings menu
  enabled: true
  # GUI title
  title: "&aPoke Settings"
  # GUI size (must be multiple of 9)
  size: 27

metrics:
  # Enable bStats metrics (anonymous usage statistics)
  # Plugin ID: 27606
  enabled: true

economy:
  # Enable economy integration (requires Vault)
  enabled: true