name: PokePlugin
version: '1.0.0'
main: com.alan.pokePlugin.PokePlugin
api-version: '1.20'
author: AlanTheDev
website: https://github.com/Eldrath-Dev
description: Nostalgic poke feature for Minecraft servers (1.20.x - 1.21.x)
softdepend: [Vault]
folia-supported: true

commands:
  poke:
    description: Poke another player
    usage: /<command> <player> | /<command> reload
    permission: poke.use

permissions:
  poke.use:
    description: Allows the use of /poke command
    default: true
  poke.bypass.cooldown:
    description: Bypass poke cooldown
    default: op
  poke.bypass.cost:
    description: Bypass poke cost
    default: op
  poke.reload:
    description: Reload the plugin configuration
    default: op